### ISSUE TITLE
Failed to load the simulation

### ISSUE THREAD

**Issue by RiccardoZuppetti** [Zhefan-Xu/isaac-go2-ros2#2]
Hi, when I try to launch the simulation from the python script, the following error is displayed:

```
[18.551s] rclpy loaded
2024-12-03 11:29:24 [18,694ms] [Warning] [pxr.OmniGraphSchema] pxr.OmniGraphSchema is deprecated - please use OmniGraphSchema instead
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/ubuntu/isaac-go2-ros2/isaac_go2_ros2.py", line 24, in run_simulator
    go2_env_cfg = Go2RSLEnvCfg()
  File "<string>", line 19, in __init__
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/utils/configclass.py", line 357, in _combined
    f1(*args, **kwargs)
  File "/home/ubuntu/isaac-go2-ros2/go2/go2_env.py", line 160, in __post_init__
    self.sim.render.antialiasing_mode = None
AttributeError: 'SimulationCfg' object has no attribute 'render'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Fatal Python error: Segmentation fault

Current thread 0x000078988e168b80 (most recent call first):
  <no Python frame>

Extension modules: omni.mdl.pymdlsdk._pymdlsdk, psutil._psutil_linux, psutil._psutil_posix, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg._cythonized_array_utils, scipy.linalg._flinalg, scipy.linalg._solve_toeplitz, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_lapack, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation, PIL._imaging, PIL._imagingft, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, _cffi_backend, osqp._osqp, multidict._multidict, yarl._quoting_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, frozenlist._frozenlist, scipy.io.matlab._mio_utils, scipy.io.matlab._streams, scipy.io.matlab._mio5_utils, yaml._yaml, cv2, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, lxml._elementpath, lxml.etree, google.protobuf.pyext._message, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, av._core, av.logging, av.bytesource, av.buffer, av.audio.format, av.enum, av.error, av.utils, av.option, av.descriptor, av.container.pyio, av.dictionary, av.format, av.stream, av.container.streams, av.sidedata.motionvectors, av.sidedata.sidedata, av.packet, av.container.input, av.container.output, av.container.core, av.codec.context, av.video.format, av.video.reformatter, av.plane, av.video.plane, av.video.frame, av.video.stream, av.codec.codec, av.frame, av.audio.layout, av.audio.plane, av.audio.frame, av.audio.stream, av.audio.fifo, av.filter.pad, av.filter.link, av.filter.context, av.filter.graph, av.filter.filter, av.audio.resampler, av.bitstream, tf2_py._tf2_py (total: 151)
/home/ubuntu/IsaacLab/_isaac_sim/python.sh: line 41:  4047 Segmentation fault      $python_exe "$@" $args
There was an error running python
```

I've launched the simulation with the following command:

```
cd <path_to_IsaacLab>
./isaaclab.sh -p <path_to_isaac-go2-ros2>/isaac_go2_ros2.py
```

since I've not installed IsaacLab within a conda env. On top, I'm running IsaacSim 4.2.0 over Ubuntu 22.04. Is there something that I can do in order to avoid the above issue?

**Comment by RiccardoZuppetti** [comment]
Verifying the Isaac Lab installation as done [here](https://isaac-sim.github.io/IsaacLab/main/source/setup/installation/pip_installation.html#verifying-the-isaac-lab-installation), it seems that everything is working fine, as shown below:

<img width="1512" alt="test" src="https://github.com/user-attachments/assets/ac8c3afd-8df6-49e9-9909-034a3806ef2b">

**Comment by Zhefan-Xu** [comment]
Thanks for the feedback! I checked your error again. Could you please try to remove the line that causes the error:
```self.sim.render.antialiasing_mode = None```
This line is not required for the sim but only to change the antialiasing mode.

**Comment by RiccardoZuppetti** [comment]
Removing that line it goes a little bit further with the loading of the simulation, but at a certain point the following error is raised now:

```
Creating window for environment.
[INFO]: Completed setting up the environment...
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/ubuntu/isaac-go2-ros2/isaac_go2_ros2.py", line 28, in run_simulator
    env, policy = go2_ctrl.get_rsl_rough_policy(go2_env_cfg)
  File "/home/ubuntu/isaac-go2-ros2/go2/go2_ctrl.py", line 82, in get_rsl_rough_policy
    env = RslRlVecEnvWrapper(env)
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/wrappers/rsl_rl/vecenv_wrapper.py", line 89, in __init__
    self.env.reset()
  File "/home/ubuntu/IsaacLab/_isaac_sim/kit/python/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_env.py", line 252, in reset
    self._reset_idx(indices)
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 348, in _reset_idx
    info = self.command_manager.reset(env_ids)
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/command_manager.py", line 326, in reset
    metrics = term.reset(env_ids=env_ids)
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/command_manager.py", line 138, in reset
    self._resample(env_ids)
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/command_manager.py", line 184, in _resample
    self._resample_command(env_ids)
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/mdp/commands/velocity_command.py", line 119, in _resample_command
    self.is_heading_env[env_ids] = r.uniform_(0.0, 1.0) <= self.cfg.rel_heading_envs
TypeError: '<=' not supported between instances of 'Tensor' and '_MISSING_TYPE'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Fatal Python error: Segmentation fault

Current thread 0x000076dd4fa26b80 (most recent call first):
  <no Python frame>

```

**Comment by RiccardoZuppetti** [comment]
Did you ever tried to install IsaacLab via pip installation in order to test if everything works fine also considering this alternative?

**Comment by RiccardoZuppetti** [comment]
> Did you ever tried to install IsaacLab via pip in order to test if everything works fine also considering this alternative?

My fault, I've installed Isaac Lab following the binary installation, the only section that I've skipped is the one related to the conda env, which is labeled as optional. Btw, I've used all day long Isaac Lab for other stuff and everything works fine, I can't really get what could be the issue there.

**Comment by RiccardoZuppetti** [comment]
Beside the issue, that finally has been solved, do you plan to add SLAM & Nav2 capabilities to the simulation framework in a future?

**Comment by Zhefan-Xu** [comment]
Glad to hear that. I might not work on ROS2 built-in SLAM and Nav2 packages but I believe they should be easy to apply if the simulation framework support ROS2 sensors (which already does). I will only update the simulator related stuffs for this repo and other SLAM/Navigation algortithms on my other repos.

**Comment by Geo0426** [comment]
I had the same question. AttributeError: 'SimulationCfg' object has no attribute 'render'. TypeError: '<=' not supported between instances of 'Tensor' and '_MISSING_TYPE' after remove the line.

**Comment by Zhefan-Xu** [comment]
> I had the same question. AttributeError: 'SimulationCfg' object has no attribute 'render'. TypeError: '<=' not supported between instances of 'Tensor' and '_MISSING_TYPE' after remove the line.

@RiccardoZuppetti Hi, could you please share how you solve this issue? it seems like it is a common issue. I would love to know what causes this and potentially fix it

**Comment by Geo0426** [comment]
> > I had the same question. AttributeError: 'SimulationCfg' object has no attribute 'render'. TypeError: '<=' not supported between instances of 'Tensor' and '_MISSING_TYPE' after remove the line.
> 
> @RiccardoZuppetti Hi, could you please share how you solve this issue? it seems like it is a common issue. I would love to know what causes this and potentially fix it

I just solved it, just git pull from the remote isaaclab repo to update my native repo. Maybe some version conflict from isaaclab, I don't know. By the way, I love this repo, it helps me a lot.

**Comment by RiccardoZuppetti** [comment]
> I just solved it, just git pull from the remote isaaclab repo to update my native repo. Maybe some version conflict from isaaclab, I don't know. By the way, I love this repo, it helps me a lot.

I'd put this aspect inside the README just to be sure that anyone uses the latest IsaacLab framework.
